version: '3.4'

services:
  frontend:
    container_name: bananarama-voting-bananza-frontend
    image: mhart/alpine-node:16
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    command: [ "yarn", "run", "sd" ]
  backend:
    container_name: bananarama-voting-bananza-backend
    image: mhart/alpine-node:16
    volumes:
      - ./backend:/app/backend
    ports:
      - 8080:8080
    working_dir: /app/backend
    command: [ "yarn", "run", "sd" ]
    environment:
      - NODE_ENV=local
